### ISSUE TITLE
HG_Core_context_destroy(): HG core handles must be freed before destroying context (256 remaining)

### ISSUE THREAD

**Issue by roblatham00** [mercury-hpc/mercury#335] opened 2020-01-21 17:25 UTC
**Describe the bug**
Recent mercury changes now result in the "margo-p2p-bw" test (and lots of others) spewing hundreds of lines about handles that are not freed.  

This did not happen a few weeks ago.  Do these errors seem like the kind of thing that would show up after some of the recent changes in mercury?

```# HG -- Error -- /tmp/cscstdm/build-stage/spack-stage-mercury-master-aa3qembnn5skb7drjreqrxnl4ryocdgm/spack-src/src/mercury_core.c:3716
 # HG_Core_context_destroy(): HG core handles must be freed before destroying context (256 remaining)
# HG -- Error -- /tmp/cscstdm/build-stage/spack-stage-mercury-master-aa3qembnn5skb7drjreqrxnl4ryocdgm/spack-src/src/mercury_core.c:3720
 # HG_Core_context_destroy(): HG core handle at address 0xe12e00 was not destroyed
# HG -- Error -- /tmp/cscstdm/build-stage/spack-stage-mercury-master-aa3qembnn5skb7drjreqrxnl4ryocdgm/spack-src/src/mercury_core.c:3720
 # HG_Core_context_destroy(): HG core handle at address 0xe12690 was not destroyed
...
# HG -- Error -- /tmp/cscstdm/build-stage/spack-stage-mercury-master-aa3qembnn5skb7drjreqrxnl4ryocdgm/spack-src/src/mercury.c:1105
 # HG_Context_destroy(): Could not destroy HG core context (HG_BUSY)
# HG -- Error -- /tmp/cscstdm/build-stage/spack-stage-mercury-master-aa3qembnn5skb7drjreqrxnl4ryocdgm/spack-src/src/mercury_core.c:1172
 # hg_core_finalize(): HG contexts must be destroyed before finalizing HG (1 remaining)
# HG -- Error -- /tmp/cscstdm/build-stage/spack-stage-mercury-master-aa3qembnn5skb7drjreqrxnl4ryocdgm/spack-src/src/mercury_core.c:3493
 # HG_Core_finalize(): Cannot finalize HG core layer
# HG -- Error -- /tmp/cscstdm/build-stage/spack-stage-mercury-master-aa3qembnn5skb7drjreqrxnl4ryocdgm/spack-src/src/mercury.c:1001
 # HG_Finalize(): Could not finalize HG core class
```

The tests appear to complete without error, but these messages completely swamp the output we're looking for.

**Comment by roblatham00** [comment] 2020-01-21 17:26
We see this in the 'margo-bw-p2p' and 'margo-latency-p2p' tests from https://xgitlab.cels.anl.gov/sds/sds-tests/tree/master/perf-regression

**Comment by soumagne** [comment] 2020-01-21 18:20
Is this the only errors that you see? Are there any errors before? It looks like you have handles that do not get freed?

**Comment by soumagne** [comment] 2020-01-21 18:22
Is it on theta?

**Comment by soumagne** [comment] 2020-01-21 20:21
I had a quick look on theta and cancellation events seem to be correctly generated for each of the receive that get cancelled so everything seems fine? Are you missing an HG_Destroy() or taking an extra refcount? It is possible that the latest changes generate more errors, that was the goal to make sure that we have better error reporting. Can you try to run that test with simply doing HG_Init() / context_create() / context_destroy() / HG_Finalize() ? i.e. run the init/finalize steps without doing any transfers?

**Comment by roblatham00** [comment] 2020-01-22 22:22
Here's a super simple margo test:  it gives the error about core handles

```
#include <assert.h>

#include <margo.h>
#include <mercury.h>

int main(int argc, char **argv)
{   
    margo_instance_id mid;
    int ret;
    
    /* actually start margo */
    mid = margo_init("gni://", MARGO_SERVER_MODE, 1, -1);
    assert(mid);
    
    margo_finalize(mid);
    
    return 0;
}
```

A very simple mercury returns without errors:
```
#include <mercury.h>

int main()
{
    hg_class_t *class = NULL;
    hg_context_t * context;
    class = HG_Init("gni://", 0);
    context = HG_Context_create(class);
    HG_Context_destroy(context);
    HG_Finalize(class);
    return 0;
}
```

**Comment by carns** [comment] 2020-01-22 22:35
The latter example is not in server mode though, right?  Does that make a difference?  I think it would be 1 as the second argument to HG_init().

**Comment by soumagne** [comment] 2020-01-22 22:51
Right should be 1, otherwise it would not create/post any handles

**Comment by soumagne** [comment] 2020-01-22 22:53
I tried that same mercury example (with listen set to 1) on theta yesterday and it was not giving me any error. I'll try the margo one.

**Comment by roblatham00** [comment] 2020-01-23 14:00
Thanks.  now with `HG_Init("gni://", 1)` I get the` core handles must be freed` error.   

So what's different between me and Jerome? 
Here is my environment:
``` Currently Loaded Modulefiles:
  1) modules/3.2.11.3
  2) alps/6.6.43-6.0.7.1_5.51__ga796da32.ari
  3) nodestat/2.3.85-6.0.7.1_5.33__gc6218bb.ari
  4) sdb/3.3.777-6.0.7.1_6.7__g5ddb0ab.ari
  5) udreg/2.3.2-6.0.7.1_5.15__g5196236.ari
  6) ugni/6.0.14.0-6.0.7.1_3.15__gea11d3d.ari
  7) gni-headers/5.0.12.0-6.0.7.1_3.13__g3b1768f.ari
  8) dmapp/7.1.1-6.0.7.1_6.6__g45d1b37.ari
  9) xpmem/2.2.15-6.0.7.1_5.13__g7549d06.ari
 10) llm/21.3.530-6.0.7.1_5.4__g3b4230e.ari
 11) nodehealth/5.6.14-6.0.7.1_8.50__gd6a82f3.ari
 12) system-config/3.5.2794-6.0.7.1_9.1__g651274ab.ari
 13) Base-opts/2.4.135-6.0.7.1_5.6__g718f891.ari
 14) gcc/8.3.0
 15) craype-mic-knl
 16) craype-network-aries
 17) craype/2.6.1
 18) cray-mpich/7.7.10
 19) rca/2.2.18-6.0.7.1_5.52__g2aa4f39.ari
 20) nompirun/nompirun
 21) darshan/3.1.5
 22) trackdeps
 23) xalt
 24) cray-libsci/19.06.1
 25) pmi/5.0.14
 26) atp/2.1.3
 27) perftools-base/7.0.5
 28) PrgEnv-gnu/6.0.5
 29) cce/9.0.2
 30) argobots-1.0rc2-gcc-7.3.0-pbfaq3h
 31) libfabric-1.9.0-gcc-7.3.0-utsfu5v
 32) mercury-master-gcc-7.3.0-aa3qemb
 33) margo-0.6.1-gcc-7.3.0-4dvjmql
 34) mpich-7.7.3-gcc-7.3.0-byrfd7f
 35) ssg-0.4.1-gcc-7.3.0-z2xzdzu
 36) libuuid-2.2.9.2-gcc-7.3.0-cgmijdc
 37) ncurses-5.9-gcc-7.3.0-wx5l2b7
 38) pmdk-1.7-gcc-7.3.0-d655y6r
 39) bake-0.3.6-gcc-7.3.0-xn727rw
```

**Comment by soumagne** [comment] 2020-01-23 17:43
Weird... I definitely do not get that error, I just did a copy/paste of your program. Here's my environment:
```
[soumagne@thetamom2 build]$ module list
Currently Loaded Modulefiles:
  1) modules/3.2.11.3
  2) alps/6.6.43-6.0.7.1_5.51__ga796da32.ari
  3) nodestat/2.3.85-6.0.7.1_5.33__gc6218bb.ari
  4) sdb/3.3.777-6.0.7.1_6.7__g5ddb0ab.ari
  5) udreg/2.3.2-6.0.7.1_5.15__g5196236.ari
  6) ugni/6.0.14.0-6.0.7.1_3.15__gea11d3d.ari
  7) gni-headers/5.0.12.0-6.0.7.1_3.13__g3b1768f.ari
  8) dmapp/7.1.1-6.0.7.1_6.6__g45d1b37.ari
  9) xpmem/2.2.15-6.0.7.1_5.13__g7549d06.ari
 10) llm/21.3.530-6.0.7.1_5.4__g3b4230e.ari
 11) nodehealth/5.6.14-6.0.7.1_8.50__gd6a82f3.ari
 12) system-config/3.5.2794-6.0.7.1_9.1__g651274ab.ari
 13) Base-opts/2.4.135-6.0.7.1_5.6__g718f891.ari
 14) gcc/8.3.0
 15) craype-mic-knl
 16) craype-network-aries
 17) craype/2.6.1
 18) cray-mpich/7.7.10
 19) rca/2.2.18-6.0.7.1_5.52__g2aa4f39.ari
 20) nompirun/nompirun
 21) darshan/3.1.5
 22) trackdeps
 23) xalt
 24) pmi/5.0.14
 25) perftools-base/7.0.5
 26) PrgEnv-gnu/6.0.5
 27) libfabric/1.9.0
```

**Comment by roblatham00** [comment] 2020-01-23 19:14
Valgrind doesn't work on Theta.  I tried '-fsanitize=address' but nothing popped out.

**Comment by soumagne** [comment] 2020-01-23 19:36
I will check in something so that you can turn on debug information more easily

**Comment by carns** [comment] 2020-01-23 20:39
@roblatham00 's environment includes libfabric and mercury built by spack (you can tell by the compiler identifier and hash in the module names):

 31) libfabric-1.9.0-gcc-7.3.0-utsfu5v
 32) mercury-master-gcc-7.3.0-aa3qemb

Are you building manually @soumagne ?  Possibly there are different options being used if so?

**Comment by soumagne** [comment] 2020-01-23 23:13
Yes I am but I am not using any particular options... I don't think that would be the issue? I just pushed a few commits, after you pull them, can you please try to do export HG_NA_LOG_LEVEL=debug and run it again? You should be able to see the recvs being canceled or not.

**Comment by roblatham00** [comment] 2020-01-24 17:33
I do see cancellations but I also get the handles-not-freed

[mercury-simple-debug.gz](https://github.com/mercury-hpc/mercury/files/4109794/mercury-simple-debug.gz)

**Comment by soumagne** [comment] 2020-01-24 17:51
Do you see that issue only on theta?

**Comment by soumagne** [comment] 2020-01-24 18:06
I think the issue is not related to OFI, look like a potential problem in the context destroy that does not wait for the handles to be fully canceled/destroyed.

**Comment by roblatham00** [comment] 2020-01-24 19:44
it's only on theta

**Comment by soumagne** [comment] 2020-01-24 19:57
I'm almost done with the fix. Cancel is async and the fact that it was forced to be sync before was hiding the issue, that's why it shows up now. Maybe some timing/scheduling difference on theta when you run but I was able to reproduce it locally by adding a sleep in the code.

**Comment by soumagne** [comment] 2020-01-24 23:50
@roblatham00 let me know if you still see the issue but should be fixed now with what I just merged.

**Closed** 2020-01-24 23:49 UTC
Labels: bug, hg, major

**Comment by roblatham00** [comment] 2020-01-26 02:43
confirmed! thanks for believing  me even when you couldn't reproduce it.
