### ISSUE TITLE
NA CCI: busy-polling with CCI/TCP

### ISSUE THREAD

**Issue by carns** [mercury-hpc/mercury#70] opened 2016-03-06 05:50 UTC
If I configure Mercury to use the CCI/TCP transport, then my server daemons consume 100% CPU (one core).  The same daemon will idle when using BMI/TCP.  This can be reproduced by running the Examples/src/example_rpc_server by itself (no clients).  It calls HG_Progress in a loop with the timeout argument set to 100.

I don't know yet if this is something in the NA layer or something in CCI itself.  Just from browsing the code, the na_cci code is not using the file descriptor poll/select method of waiting for events even when the timeout > 0, so that might be all that's needed but I'm not certain.

**Comment by soumagne** [comment] 2016-03-06 19:48
OK yes this is something that I had taken care of when implementing the BMI plugin. I don't think there is any problems in the NA layer so that must come from the CCI plugin or CCI itself, although CCI is probably doing the right thing.

**Comment by soumagne** [comment] 2016-03-07 18:57
OK we might want to include Scott on that then.

**Comment by carns** [comment] 2016-03-07 18:59
We can do this the github way by mentioning @scottatchley in the issue :)

**Comment by soumagne** [comment] 2016-03-07 19:02
@carns OK. Well it looks like you've just done it :)
@scottatchley Scott, is the problem mentioned in that issue something that you are already aware of?

**Comment by scottatchley** [comment] 2016-03-07 19:34
Adding in @gvallee

Geoffroy,

Are your TCP blocking commits all in master?

We may need to use the file descriptor in na_cci. :-)

**Comment by scottatchley** [comment] 2016-03-07 19:56
Answering my own question, his changes are in.

na_cci needs to be modified. I am trying to push a branch. I am not sure I have permissions.

**Comment by carns** [comment] 2016-03-07 20:04
@scottatchley, I've had good luck (in terms of development practice) by forking Mercury, making my changes in a branch on that fork, then opening a pull request.  It's pretty easy and it gives Jerome a chance to look over it, comment, and figure out where to land it.

**Comment by soumagne** [comment] 2016-03-07 20:39
@scottatchley I added you as an external collaborator so you should also have write access to the repo now. I'm fine with both, fork + pull request or push to topic_xxx branch in the main repo. The nice thing with the pull request is that it also triggers the travis continuous testing at the same time so we know before committing/merging that the tests pass.

**Comment by scottatchley** [comment] 2016-03-07 20:59
I cloned, committed, and pushed to my repo. I opened a pull request.

**Comment by soumagne** [comment] 2016-03-07 21:26
Hmm I just gave it a try and there is still a problem I think. If I run the mercury test server `hg_test_server -c cci`, I'm still at 100% cpu. I attached the debugger and it seems that the problem is here in na_cci_progress:
```
		poll(&pfd, 1, ((int) remaining) * 1000);
		hg_time_get_current(&t1);
		rc = cci_get_event(e, &event);
```
Although remaining/timeout is 0, we're now blocking in cci_get_event() which also puts CPU core to 100%

**Comment by carns** [comment] 2016-03-07 22:18
I don't know if this is related or not (I'm not able to dig into it with a debugger right now), but I'll mention it in case it is helpful. I also see 100% cpu usage when I run "pingpong -s -b" from CCI using the current git master, without using Mercury.  From looking at the source I think -b is intended to make the caller (pingpong program in this case) block on a file descriptor similarly to the na_cci patch.

**Comment by scottatchley** [comment] 2016-03-07 22:26
I am at LLNL all week in presentations. I will try to look at it tomorrow morning.

**Comment by soumagne** [comment] 2016-05-13 17:51
Scott, I was just wondering, were you able to look at that? Thanks.

**Comment by scottatchley** [comment] 2016-05-17 10:54
Hi Jerome,

The TCP progress thread is polling all the time. We need to switch it to use poll() internally on all of the connections’ sockets.

Scott

**Closed** 2018-10-17 05:29 UTC
Labels: bug, major, na, wontfix
